# Generated by Django 5.0.1 on 2024-02-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='registration_key',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
