# Generated by Django 5.0.1 on 2024-03-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='avatar',
            field=models.ImageField(default='avatar_images/pp.jpg', upload_to='avatar_images'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='avatar',
            field=models.ImageField(default='avatar_images/pp.jpg', upload_to='avatar_images'),
        ),
        migrations.AddField(
            model_name='publicprofile',
            name='avatar',
            field=models.ImageField(default='avatar_images/pp.jpg', upload_to='avatar_images'),
        ),
    ]
