# Generated by Django 5.0.1 on 2024-05-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CondoUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=4)),
                ('size', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('extra_information', models.TextField(null=True)),
                ('operational_expense', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('image', models.ImageField(default='condoUnit_images/defaultCondoUnit.jpg', upload_to='condoUnit_images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.IntegerField()),
                ('start_time', models.TimeField(help_text='Opening time of the facility')),
                ('end_time', models.TimeField(help_text='Closing time of the facility')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=4)),
                ('size', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('extra_information', models.TextField(null=True)),
                ('operational_expense', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('image', models.ImageField(default='parkingUnit_images/defaultParkingUnit.jpg', upload_to='parkingUnit_images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=12)),
                ('fee_rate', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('image', models.ImageField(default='property_images/defaultProperty.jpg', upload_to='property_images')),
            ],
        ),
        migrations.CreateModel(
            name='StorageUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=4)),
                ('size', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('extra_information', models.TextField(null=True)),
                ('operational_expense', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('image', models.ImageField(default='storageUnit_images/defaultStorageUnit.jpg', upload_to='storageUnit_images')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
