# Generated by Django 5.0.1 on 2024-02-28 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0002_remove_companyprofile_id_remove_employeeprofile_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_profiles', to='user_profile.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_units', to='properties.propertyprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CondoUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condo_units', to='properties.propertyprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorageUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_units', to='properties.propertyprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
