# Generated by Django 5.0.1 on 2024-05-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condounit',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parkingunit',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='storageunit',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
