# Generated by Django 5.0.1 on 2024-03-04 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
        ('user_profile', '0002_companyprofile_avatar_employeeprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condounit',
            name='extra_information',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='condounit',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condo_units', to='user_profile.publicprofile'),
        ),
        migrations.AddField(
            model_name='condounit',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='parkingunit',
            name='extra_information',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='parkingunit',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_units', to='user_profile.publicprofile'),
        ),
        migrations.AddField(
            model_name='parkingunit',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='storageunit',
            name='extra_information',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='storageunit',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_units', to='user_profile.publicprofile'),
        ),
        migrations.AddField(
            model_name='storageunit',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
