# Generated by Django 5.0.1 on 2024-03-04 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_condounit_extra_information_condounit_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condounit',
            old_name='owner',
            new_name='public_profile',
        ),
        migrations.RenameField(
            model_name='parkingunit',
            old_name='owner',
            new_name='public_profile',
        ),
        migrations.RenameField(
            model_name='storageunit',
            old_name='owner',
            new_name='public_profile',
        ),
    ]
