# Generated by Django 5.0.1 on 2024-05-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('request_description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('completion_information', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In_Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('type', models.CharField(choices=[('MOVE_IN', 'Move In'), ('MOVE_OUT', 'Move Out'), ('REPAIR', 'Repair'), ('ACCESS', 'Access'), ('INTERCOM', 'Intercom'), ('VIOLATION', 'Violation'), ('DEFFIENCY', 'Deffiency'), ('MISCELANIOUS', 'Miscelanious')], default='MISCELANIOUS', max_length=20)),
            ],
            options={
                'ordering': ['request_date'],
            },
        ),
    ]
