# Generated by Django 5.0.1 on 2024-05-01 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('properties', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_profile.employeeprofile'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='public_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='user_profile.publicprofile'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='properties.condounit'),
        ),
    ]
