# Generated by Django 5.0.1 on 2024-05-02 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_servicerequest_assigned_employee'),
        ('properties', '0003_alter_condounit_location_alter_parkingunit_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='properties.condounit'),
        ),
    ]
