# Generated by Django 5.0.1 on 2024-03-21 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_initial'),
        ('registration_key', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condoregistrationkey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.publicprofile'),
        ),
        migrations.AddField(
            model_name='parkingregistrationkey',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.parkingunit'),
        ),
        migrations.AddField(
            model_name='parkingregistrationkey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.publicprofile'),
        ),
        migrations.AddField(
            model_name='storageregistrationkey',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.storageunit'),
        ),
        migrations.AddField(
            model_name='storageregistrationkey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.publicprofile'),
        ),
    ]
